# Jekyll configuration
permalink                : /:categories/:title/
lsi                      : false
future                   : false
show_drafts              : false
kramdown:
  toc_levels             : 1..3
  input                  : GFM
  hard_wrap              : false
  auto_ids               : true
  entity_output          : as_char
  smart_quotes           : lsquo,rsquo,ldquo,rdquo
  enable_coderay         : false
highlighter              : rouge
keep_files:
  - .git
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock

# Setup
title:                Djerry
tagline:             'Djerry Security'
description-en:      'Devote to Information Security&Countermeasure Research'
description-ch:      '致力于信息安全和对抗技术研究'
url:                  djerrystyle.github.io
baseurl:              /
note_title:           "最新状态"
note_content:         "Do u Improve Ur Design,Or u do SOmE news"
note_time:            "8月 16号"

author:
  name:               'Djerry'
  url:                 djerrystyle.github.io

# Plugins
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-paginate-v2

googleAnalyticsId: UA-102824548-1

defaults:
  # Blog Articles
  - scope:
      path: _posts/university
      type: posts
    values:
      layout: post
      category: post-university
      read_time: true
      support: true
      breadcrumbs:
        - label: "Blog Articles"
          url: /university/
   # study
  - scope:
      path: _posts/study
      type: posts
    values:
      layout: post
      category: post-study
      read_time: true
      comments: true
      support: true
      breadcrumbs:
        - label: "study"
          url: /study/
  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: page

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled      : true
  debug        : false
  per_page     : 4
  permalink    : "/page/:num/"
  title        : ":title - Page :num of :max"
  limit        : 0
  sort_field   : "date"
  sort_reverse : true

  
# Plugin: Auto Pages (jekyll-paginate-v2)
autopages:
  enabled      : false
  categories:
    enabled    : false
  collections:
    enabled    : false
  tags:
    enabled    : false
    layouts:
      - "autopage_tags.html"
    title      : ":tag" # :tag is replaced by the tag name
    permalink  : "/tag/:tag"
     
# Staticman
staticmanUrl: https://api.staticman.net/v2/entry/djerrystyle/djerrystyle.github.io/master/comments

rsa: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDhDpeMnZQ8cduyMfMw2N0YoP4BwZomUe9Uo8RIFKYw0pSGLUpGq3GgWiCQLDp6yfjVOugJ9H7OdMOxkQbNdbkTv8XElOaJKBPiROciFnIUuyXaPJH957WRLxN1xINJfwLBFvxUZWrIttHIttnBkGQiizHmTIAEI+cgtBuDlKagWQIDAQAB"
